# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
    

pool: server
stages:
  - stage: 'Build'

jobs:
-job:Build1
steps:
- task: ServiceNow-DevOps-Agent-Job-Notification@1
  inputs:
    connectedServiceName: 'dev211826-kavyapersonal devops project1-ServiceNow DevOps Service Connection'
    Phase: 'STARTED'

- task: ServiceNow-DevOps-Agent-Job-Notification@1
  inputs:
    connectedServiceName: 'Devopssnowconnection1'
    Phase: 'COMPLETED'