# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - none
stages:
- stage: One
  displayName: Upload Configuration Data
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: A
    displayName: Upload
    steps:
    - task: ServiceNow-DevOps-Config-Agent-Upload-Config@1
      name: componentUpload
      inputs:
        connectedServiceName: 'MyServiceNowInstance'
        applicationName: 'PaymentDemo'
        uploadTarget: 'component'
        configFile: 'k8s/helm/values.yml'
        namePath: 'processor-api-v1.0'
        dataFormat: 'yaml'
        autoValidate: true
        autoCommit: true
        convertPath: true